{
  "name": "NTParkVisits",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-AU",
    "sourceQueryCulture": "en-AU",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "tables": [
      {
        "name": "Visits",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Park",
            "dataType": "string",
            "sourceColumn": "Park",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Visits",
            "dataType": "int64",
            "sourceColumn": "Visits",
            "summarizeBy": "none",
            "formatString": "#,0"
          }
        ],
        "measures": [
          {
            "name": "Total Visits",
            "expression": "SUM(Visits[Visits])",
            "formatString": "#,0"
          },
          {
            "name": "Selected Year",
            "expression": "MAX('Year'[Year])",
            "formatString": "0"
          },
          {
            "name": "Selected Year Visits",
            "expression": "VAR Y = [Selected Year]\nRETURN CALCULATE([Total Visits], REMOVEFILTERS('Year'), 'Year'[Year] = Y)",
            "formatString": "#,0"
          },
          {
            "name": "Previous Year Visits",
            "expression": "VAR Y = [Selected Year]\nRETURN CALCULATE([Total Visits], REMOVEFILTERS('Year'), 'Year'[Year] = Y - 1)",
            "formatString": "#,0"
          },
          {
            "name": "YoY Change",
            "expression": "DIVIDE([Selected Year Visits] - [Previous Year Visits], [Previous Year Visits])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Visit Change",
            "expression": "IF(NOT ISBLANK([Previous Year Visits]), [Selected Year Visits] - [Previous Year Visits])",
            "formatString": "+#,0;-#,0;0"
          }
        ],
        "partitions": [
          {
            "name": "Visits",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(Binary.FromText(\"WWVhcixSZWdpb24sUGFyayxWaXNpdHMKMjAyMSxEYXJ3aW4sQmVycnkgU3ByaW5ncyBOYXR1cmUgUmVzZXJ2ZSwxNTg1MDAKMjAyMixEYXJ3aW4sQmVycnkgU3ByaW5ncyBOYXR1cmUgUmVzZXJ2ZSwyMDQxMDAKMjAyMyxEYXJ3aW4sQmVycnkgU3ByaW5ncyBOYXR1cmUgUmVzZXJ2ZSwxNzkzMDAKMjAyNCxEYXJ3aW4sQmVycnkgU3ByaW5ncyBOYXR1cmUgUmVzZXJ2ZSwxNzU4MDAKMjAyNSxEYXJ3aW4sQmVycnkgU3ByaW5ncyBOYXR1cmUgUmVzZXJ2ZSwxODY2MDAKMjAyMSxEYXJ3aW4sQ2FzdWFyaW5hIENvYXN0YWwgUmVzZXJ2ZSAtIFdob2xlIG9mIFBhcmssMTQ1MjgwMAoyMDIyLERhcndpbixDYXN1YXJpbmEgQ29hc3RhbCBSZXNlcnZlIC0gV2hvbGUgb2YgUGFyaywxNDExMzAwCjIwMjMsRGFyd2luLENhc3VhcmluYSBDb2FzdGFsIFJlc2VydmUgLSBXaG9sZSBvZiBQYXJrLDEzNTcwMDAKMjAyNCxEYXJ3aW4sQ2FzdWFyaW5hIENvYXN0YWwgUmVzZXJ2ZSAtIFdob2xlIG9mIFBhcmssMTM0NjAwMAoyMDI1LERhcndpbixDYXN1YXJpbmEgQ29hc3RhbCBSZXNlcnZlIC0gV2hvbGUgb2YgUGFyaywxNDIyMjAwCjIwMjEsRGFyd2luLEZvZ2cgRGFtIENvbnNlcnZhdGlvbiBSZXNlcnZlLDUxNTAwCjIwMjIsRGFyd2luLEZvZ2cgRGFtIENvbnNlcnZhdGlvbiBSZXNlcnZlLDY1NzAwCjIwMjMsRGFyd2luLEZvZ2cgRGFtIENvbnNlcnZhdGlvbiBSZXNlcnZlLDU3NDAwCjIwMjQsRGFyd2luLEZvZ2cgRGFtIENvbnNlcnZhdGlvbiBSZXNlcnZlLDY5MzAwCjIwMjUsRGFyd2luLEZvZ2cgRGFtIENvbnNlcnZhdGlvbiBSZXNlcnZlLDU1NzAwCjIwMjEsRGFyd2luLEhvd2FyZCBTcHJpbmdzIE5hdHVyZSBQYXJrLDExOTYwMAoyMDIyLERhcndpbixIb3dhcmQgU3ByaW5ncyBOYXR1cmUgUGFyaywxMzQ1MDAKMjAyMyxEYXJ3aW4sSG93YXJkIFNwcmluZ3MgTmF0dXJlIFBhcmssMTM3ODAwCjIwMjQsRGFyd2luLEhvd2FyZCBTcHJpbmdzIE5hdHVyZSBQYXJrLDEyMDcwMAoyMDI1LERhcndpbixIb3dhcmQgU3ByaW5ncyBOYXR1cmUgUGFyaywxMjY2MDAKMjAyMSxEYXJ3aW4sTGl0Y2hmaWVsZCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyNzQ0MDAKMjAyMixEYXJ3aW4sTGl0Y2hmaWVsZCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywzNjc2MDAKMjAyMyxEYXJ3aW4sTGl0Y2hmaWVsZCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyNTM0MDAKMjAyNCxEYXJ3aW4sTGl0Y2hmaWVsZCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyNDQyMDAKMjAyNSxEYXJ3aW4sTGl0Y2hmaWVsZCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyODAxMDAKMjAyMSxEYXJ3aW4sTWFyeSBSaXZlciBOYXRpb25hbCBQYXJrIC0gU2hhZHkgQ2FtcCBDb25zZXJ2YXRpb24gUmVzZXJ2ZSwzNzQwMAoyMDIyLERhcndpbixNYXJ5IFJpdmVyIE5hdGlvbmFsIFBhcmsgLSBTaGFkeSBDYW1wIENvbnNlcnZhdGlvbiBSZXNlcnZlLDQzNTAwCjIwMjMsRGFyd2luLE1hcnkgUml2ZXIgTmF0aW9uYWwgUGFyayAtIFNoYWR5IENhbXAgQ29uc2VydmF0aW9uIFJlc2VydmUsMzkwMDAKMjAyNCxEYXJ3aW4sTWFyeSBSaXZlciBOYXRpb25hbCBQYXJrIC0gU2hhZHkgQ2FtcCBDb25zZXJ2YXRpb24gUmVzZXJ2ZSwzNDQwMAoyMDI1LERhcndpbixNYXJ5IFJpdmVyIE5hdGlvbmFsIFBhcmsgLSBTaGFkeSBDYW1wIENvbnNlcnZhdGlvbiBSZXNlcnZlLDMyMzAwCjIwMjEsS2F0aGVyaW5lLEN1dHRhIEN1dHRhIENhdmVzIE5hdHVyZSBQYXJrLDEzNDAwCjIwMjIsS2F0aGVyaW5lLEN1dHRhIEN1dHRhIENhdmVzIE5hdHVyZSBQYXJrLDE3MjAwCjIwMjMsS2F0aGVyaW5lLEN1dHRhIEN1dHRhIENhdmVzIE5hdHVyZSBQYXJrLDExNTAwCjIwMjQsS2F0aGVyaW5lLEN1dHRhIEN1dHRhIENhdmVzIE5hdHVyZSBQYXJrLDEwMjAwCjIwMjUsS2F0aGVyaW5lLEN1dHRhIEN1dHRhIENhdmVzIE5hdHVyZSBQYXJrLDEwNDAwCjIwMjEsS2F0aGVyaW5lLEVsc2V5IE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDIzMjUwMAoyMDIyLEthdGhlcmluZSxFbHNleSBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyMDc3MDAKMjAyMyxLYXRoZXJpbmUsRWxzZXkgTmF0aW9uYWwgUGFyayAtIFdob2xlIG9mIFBhcmssMjU1NDAwCjIwMjQsS2F0aGVyaW5lLEVsc2V5IE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDIwMTYwMAoyMDI1LEthdGhlcmluZSxFbHNleSBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywxNDY4MDAKMjAyMSxLYXRoZXJpbmUsSnVkYmFycmEvR3JlZ29yeSBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyayw0ODAwMAoyMDIyLEthdGhlcmluZSxKdWRiYXJyYS9HcmVnb3J5IE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDQ5NjAwCjIwMjMsS2F0aGVyaW5lLEp1ZGJhcnJhL0dyZWdvcnkgTmF0aW9uYWwgUGFyayAtIFdob2xlIG9mIFBhcmssNDYwMDAKMjAyNCxLYXRoZXJpbmUsSnVkYmFycmEvR3JlZ29yeSBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywzNzMwMAoyMDI1LEthdGhlcmluZSxKdWRiYXJyYS9HcmVnb3J5IE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDQzOTAwCjIwMjEsS2F0aGVyaW5lLEtlZXAgUml2ZXIgTmF0aW9uYWwgUGFyaywyMDIwMAoyMDIyLEthdGhlcmluZSxLZWVwIFJpdmVyIE5hdGlvbmFsIFBhcmssMjMyMDAKMjAyMyxLYXRoZXJpbmUsS2VlcCBSaXZlciBOYXRpb25hbCBQYXJrLDExNzAwCjIwMjQsS2F0aGVyaW5lLEtlZXAgUml2ZXIgTmF0aW9uYWwgUGFyaywxNDEwMAoyMDI1LEthdGhlcmluZSxLZWVwIFJpdmVyIE5hdGlvbmFsIFBhcmssMTM0MDAKMjAyMSxLYXRoZXJpbmUsTGltbWVuIE5hdGlvbmFsIFBhcmsgLSBIb2Rnc29uIFJpdmVyIENyb3NzaW5nLDExNjAwCjIwMjIsS2F0aGVyaW5lLExpbW1lbiBOYXRpb25hbCBQYXJrIC0gSG9kZ3NvbiBSaXZlciBDcm9zc2luZywxMDEwMAoyMDIzLEthdGhlcmluZSxMaW1tZW4gTmF0aW9uYWwgUGFyayAtIEhvZGdzb24gUml2ZXIgQ3Jvc3NpbmcsOTQwMAoyMDI0LEthdGhlcmluZSxMaW1tZW4gTmF0aW9uYWwgUGFyayAtIEhvZGdzb24gUml2ZXIgQ3Jvc3NpbmcsOTgwMAoyMDI1LEthdGhlcmluZSxMaW1tZW4gTmF0aW9uYWwgUGFyayAtIEhvZGdzb24gUml2ZXIgQ3Jvc3NpbmcsOTYwMAoyMDIxLEthdGhlcmluZSxOaXRtaWx1ayBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyNzE3MDAKMjAyMixLYXRoZXJpbmUsTml0bWlsdWsgTmF0aW9uYWwgUGFyayAtIFdob2xlIG9mIFBhcmssMzA5ODAwCjIwMjMsS2F0aGVyaW5lLE5pdG1pbHVrIE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDI2NjIwMAoyMDI0LEthdGhlcmluZSxOaXRtaWx1ayBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywyNTk4MDAKMjAyNSxLYXRoZXJpbmUsTml0bWlsdWsgTmF0aW9uYWwgUGFyayAtIFdob2xlIG9mIFBhcmssMjUxMjAwCjIwMjEsQmFya2x5LEthcmx1IEthcmx1IChEZXZpbHMgTWFyYmxlcykgQ29uc2VydmF0aW9uIFJlc2VydmUsMTQ2MzAwCjIwMjIsQmFya2x5LEthcmx1IEthcmx1IChEZXZpbHMgTWFyYmxlcykgQ29uc2VydmF0aW9uIFJlc2VydmUsOTk0MDAKMjAyMyxCYXJrbHksS2FybHUgS2FybHUgKERldmlscyBNYXJibGVzKSBDb25zZXJ2YXRpb24gUmVzZXJ2ZSwyMjUyMDAKMjAyNCxCYXJrbHksS2FybHUgS2FybHUgKERldmlscyBNYXJibGVzKSBDb25zZXJ2YXRpb24gUmVzZXJ2ZSw5ODgwMAoyMDI1LEJhcmtseSxLYXJsdSBLYXJsdSAoRGV2aWxzIE1hcmJsZXMpIENvbnNlcnZhdGlvbiBSZXNlcnZlLDExMDEwMAoyMDIxLEJhcmtseSxUZW5uYW50IENyZWVrIFRlbGVncmFwaCBTdGF0aW9uLDE1MjAwCjIwMjIsQmFya2x5LFRlbm5hbnQgQ3JlZWsgVGVsZWdyYXBoIFN0YXRpb24sMTk2MDAKMjAyMyxCYXJrbHksVGVubmFudCBDcmVlayBUZWxlZ3JhcGggU3RhdGlvbiwxNDAwMAoyMDI0LEJhcmtseSxUZW5uYW50IENyZWVrIFRlbGVncmFwaCBTdGF0aW9uLDE5MzAwCjIwMjUsQmFya2x5LFRlbm5hbnQgQ3JlZWsgVGVsZWdyYXBoIFN0YXRpb24sMTgzMDAKMjAyMSxBbGljZSBTcHJpbmdzLEFsaWNlIFNwcmluZ3MgVGVsZWdyYXBoIFN0YXRpb24gSGlzdG9yaWNhbCBSZXNlcnZlLDE4MzQwMAoyMDIyLEFsaWNlIFNwcmluZ3MsQWxpY2UgU3ByaW5ncyBUZWxlZ3JhcGggU3RhdGlvbiBIaXN0b3JpY2FsIFJlc2VydmUsMTg3NDAwCjIwMjMsQWxpY2UgU3ByaW5ncyxBbGljZSBTcHJpbmdzIFRlbGVncmFwaCBTdGF0aW9uIEhpc3RvcmljYWwgUmVzZXJ2ZSwxODAyMDAKMjAyNCxBbGljZSBTcHJpbmdzLEFsaWNlIFNwcmluZ3MgVGVsZWdyYXBoIFN0YXRpb24gSGlzdG9yaWNhbCBSZXNlcnZlLDE0MjkwMAoyMDI1LEFsaWNlIFNwcmluZ3MsQWxpY2UgU3ByaW5ncyBUZWxlZ3JhcGggU3RhdGlvbiBIaXN0b3JpY2FsIFJlc2VydmUsMTk3ODAwCjIwMjEsQWxpY2UgU3ByaW5ncyxBcmx0dW5nYSBIaXN0b3JpY2FsIFJlc2VydmUsNzMwMAoyMDIyLEFsaWNlIFNwcmluZ3MsQXJsdHVuZ2EgSGlzdG9yaWNhbCBSZXNlcnZlLDExNzAwCjIwMjMsQWxpY2UgU3ByaW5ncyxBcmx0dW5nYSBIaXN0b3JpY2FsIFJlc2VydmUsMTA3MDAKMjAyNCxBbGljZSBTcHJpbmdzLEFybHR1bmdhIEhpc3RvcmljYWwgUmVzZXJ2ZSwxMDgwMAoyMDI1LEFsaWNlIFNwcmluZ3MsQXJsdHVuZ2EgSGlzdG9yaWNhbCBSZXNlcnZlLDQxODAwCjIwMjEsQWxpY2UgU3ByaW5ncyxDaGFtYmVycyBQaWxsYXIgSGlzdG9yaWNhbCBSZXNlcnZlLDM3MDAKMjAyMixBbGljZSBTcHJpbmdzLENoYW1iZXJzIFBpbGxhciBIaXN0b3JpY2FsIFJlc2VydmUsMzAwMAoyMDIzLEFsaWNlIFNwcmluZ3MsQ2hhbWJlcnMgUGlsbGFyIEhpc3RvcmljYWwgUmVzZXJ2ZSwyNTAwCjIwMjQsQWxpY2UgU3ByaW5ncyxDaGFtYmVycyBQaWxsYXIgSGlzdG9yaWNhbCBSZXNlcnZlLDIwMDAKMjAyNSxBbGljZSBTcHJpbmdzLENoYW1iZXJzIFBpbGxhciBIaXN0b3JpY2FsIFJlc2VydmUsMjIwMAoyMDIxLEFsaWNlIFNwcmluZ3MsRmlua2UgR29yZ2UgTmF0aW9uYWwgUGFyaywxODEwMAoyMDIyLEFsaWNlIFNwcmluZ3MsRmlua2UgR29yZ2UgTmF0aW9uYWwgUGFyaywxODAwMAoyMDIzLEFsaWNlIFNwcmluZ3MsRmlua2UgR29yZ2UgTmF0aW9uYWwgUGFyaywxNDQwMAoyMDI0LEFsaWNlIFNwcmluZ3MsRmlua2UgR29yZ2UgTmF0aW9uYWwgUGFyaywxMzQwMAoyMDI1LEFsaWNlIFNwcmluZ3MsRmlua2UgR29yZ2UgTmF0aW9uYWwgUGFyaywxOTAwMAoyMDIxLEFsaWNlIFNwcmluZ3MsUmFpbmJvdyBWYWxsZXkgQ29uc2VydmF0aW9uIFJlc2VydmUsMTAzMDAKMjAyMixBbGljZSBTcHJpbmdzLFJhaW5ib3cgVmFsbGV5IENvbnNlcnZhdGlvbiBSZXNlcnZlLDgyMDAKMjAyMyxBbGljZSBTcHJpbmdzLFJhaW5ib3cgVmFsbGV5IENvbnNlcnZhdGlvbiBSZXNlcnZlLDgwMDAKMjAyNCxBbGljZSBTcHJpbmdzLFJhaW5ib3cgVmFsbGV5IENvbnNlcnZhdGlvbiBSZXNlcnZlLDY1MDAKMjAyNSxBbGljZSBTcHJpbmdzLFJhaW5ib3cgVmFsbGV5IENvbnNlcnZhdGlvbiBSZXNlcnZlLDcwMDAKMjAyMSxBbGljZSBTcHJpbmdzLFRyZXBoaW5hIEdvcmdlIE5hdHVyZSBQYXJrLDI1NjAwCjIwMjIsQWxpY2UgU3ByaW5ncyxUcmVwaGluYSBHb3JnZSBOYXR1cmUgUGFyaywyNTcwMAoyMDIzLEFsaWNlIFNwcmluZ3MsVHJlcGhpbmEgR29yZ2UgTmF0dXJlIFBhcmssMzIxMDAKMjAyNCxBbGljZSBTcHJpbmdzLFRyZXBoaW5hIEdvcmdlIE5hdHVyZSBQYXJrLDMzODAwCjIwMjUsQWxpY2UgU3ByaW5ncyxUcmVwaGluYSBHb3JnZSBOYXR1cmUgUGFyaywzODUwMAoyMDIxLEFsaWNlIFNwcmluZ3MsV2F0YXJya2EgTmF0aW9uYWwgUGFyaywxMTM4MDAKMjAyMixBbGljZSBTcHJpbmdzLFdhdGFycmthIE5hdGlvbmFsIFBhcmssMTk2NzAwCjIwMjMsQWxpY2UgU3ByaW5ncyxXYXRhcnJrYSBOYXRpb25hbCBQYXJrLDE4NjgwMAoyMDI0LEFsaWNlIFNwcmluZ3MsV2F0YXJya2EgTmF0aW9uYWwgUGFyaywxOTM1MDAKMjAyNSxBbGljZSBTcHJpbmdzLFdhdGFycmthIE5hdGlvbmFsIFBhcmssMjA4OTAwCjIwMjEsQWxpY2UgU3ByaW5ncyxUam9yaXRqYSAvIFdlc3QgTWFjRG9ubmVsbCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywxMjYxMDAKMjAyMixBbGljZSBTcHJpbmdzLFRqb3JpdGphIC8gV2VzdCBNYWNEb25uZWxsIE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDE3MDYwMAoyMDIzLEFsaWNlIFNwcmluZ3MsVGpvcml0amEgLyBXZXN0IE1hY0Rvbm5lbGwgTmF0aW9uYWwgUGFyayAtIFdob2xlIG9mIFBhcmssMTU1NTAwCjIwMjQsQWxpY2UgU3ByaW5ncyxUam9yaXRqYSAvIFdlc3QgTWFjRG9ubmVsbCBOYXRpb25hbCBQYXJrIC0gV2hvbGUgb2YgUGFyaywxNDU0MDAKMjAyNSxBbGljZSBTcHJpbmdzLFRqb3JpdGphIC8gV2VzdCBNYWNEb25uZWxsIE5hdGlvbmFsIFBhcmsgLSBXaG9sZSBvZiBQYXJrLDEzNzMwMAo=\", BinaryEncoding.Base64), [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Year\", Int64.Type}, {\"Region\", type text}, {\"Park\", type text}, {\"Visits\", Int64.Type}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Year",
        "columns": [
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "isKey": true,
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "Year",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "#table(type table [Year = Int64.Type], {{2021}, {2022}, {2023}, {2024}, {2025}})"
              ]
            }
          }
        ]
      },
      {
        "name": "Park",
        "columns": [
          {
            "name": "Park",
            "dataType": "string",
            "sourceColumn": "Park",
            "summarizeBy": "none",
            "isKey": true
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Park",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "Table.Distinct(Table.SelectColumns(Visits, {\"Park\", \"Region\"}))"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "Visits_Year",
        "fromTable": "Visits",
        "fromColumn": "Year",
        "toTable": "Year",
        "toColumn": "Year",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "Visits_Park",
        "fromTable": "Visits",
        "fromColumn": "Park",
        "toTable": "Park",
        "toColumn": "Park",
        "fromCardinality": "many",
        "toCardinality": "one",
        "crossFilteringBehavior": "oneDirection"
      }
    ]
  }
}
